default_language_version:
  python: python3.6
repos:
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.0.1
  hooks:
  - id: reorder-python-imports
    args: [--py3-plus]
- repo: https://github.com/asottile/pyupgrade
  rev: v2.31.1
  hooks:
  - id: pyupgrade
    args: [--py36-plus]
- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
  - id: black
    args: [--line-length, "119"]
    require_serial: true
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: debug-statements
  - id: flake8
